### ISSUE TITLE
npm run dev not woriking

### ISSUE THREAD

**Issue by davidperroud** [sn8/yii2-vuejs-crud#1]
npm run dev not found

sh: cross-env: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/perrouddavid/.npm/_logs/2019-11-01T08_12_52_370Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/perrouddavid/.npm/_logs/2019-11-01T08_12_52_388Z-debug.log
MacBook-Pro-de-David:yiivue perrouddavid$

**Comment by sn8** [comment]
Thanks David, I fixed it now.

**Comment by davidperroud** [comment]
Thank you ! I’ll try again this evening :)
